import Head from 'next/head'
import LazyVideo from '@/components/Lazyvideo'


export default function Home() {
	return (
		<>
			<Head>
				<title>Lazy Video Sample Page</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div style={{ display: 'flex', justifyContent: 'center' , flexDirection: 'column' }}>
				<LazyVideo src='/movie.mp4' />
				<LazyVideo src='/movie.mp4' />
				<LazyVideo src='/movie.mp4' />
				<LazyVideo src='/movie.mp4' />
				<LazyVideo src='/movie.mp4' />
				<LazyVideo src='/movie.mp4' />
				<LazyVideo src='/movie.mp4' />
				<LazyVideo src='/movie.mp4' />
				<LazyVideo src='/movie.mp4' />
			</div>
		</>
	)
}
